// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NgoProject.Context;

#nullable disable

namespace NgoProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231222081138_ngochai1")]
    partial class ngochai1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NgoProject.Models.BannerTable", b =>
                {
                    b.Property<int>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOne"));

                    b.Property<string>("ContentOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleOne")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOne");

                    b.ToTable("banner");
                });

            modelBuilder.Entity("NgoProject.Models.BannerTabless", b =>
                {
                    b.Property<int>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTwo"));

                    b.Property<string>("ContentTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleTwo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTwo");

                    b.ToTable("bannerss");
                });
#pragma warning restore 612, 618
        }
    }
}
